name: Scan

on:
  push:
  pull_request:
    branches: [ master, development ]

jobs:

  scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build the image
      id: build
      run: |
        docker build . -f ./Dockerfile -t hms-dbmi/fhirquestionnaire:latest

    - name: Run Snyk to check Docker image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/docker@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: hms-dbmi/fhirquestionnaire:latest
        args: --file=Dockerfile

    #- name: Upload result to GitHub Code Scanning
    #  uses: github/codeql-action/upload-sarif@v1
    #  with:
    #    sarif_file: snyk.sarif
