name: Test Image Build

on:
  workflow_dispatch:

jobs:
  test:
    uses: hms-dbmi/actions/.github/workflows/test-image-build.yml@main
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    with:
      repository: ${{ github.repository }}
      commit: ${{ github.sha }}
